#!/bin/bash
function g.br {
  br=`git branch | grep "*"`
  echo ${br/* /}
}


#lamp
alias a2='sudo service apache2'
alias vhosts='sudo mc /etc/apache2/'
alias debug="export XDEBUG_CONFIG='idekey=PHPSTORM remote_host=localhost';export SERVER_PORT=80;export SERVER_NAME=localhost;export REQUEST_URI=localhost"
alias undebug="unset XDEBUG_CONFIG;unset SERVER_PORT;unset SERVER_NAME;unset REQUEST_URI"

#symfony
alias s='./symfony'
alias d='doctrine'
alias s.cc='s cc'
alias sf='./app/console'
alias sf.cc="sf cache:clear"
alias sf.gb='sf generate:bundle'
alias sf.ge='sf doctrine:generate:entity'
alias sf.gc='sf doctrine:generate:crud'
alias sf.su='sf doctrine:schema:update --force'
alias sf.fl='sf doctrine:fixtures:load'
function sf.dda {
  sf doctrine:query:dql "$*" --hydrate="array"
}
function sf.dd {
  sf doctrine:query:dql "$*"
}

function d.d {
  s doctrine:dql "$*"
}

alias d.m='s doctrine:migrate'
alias d.md='s doctrine:migrate --down'
alias d.mu='s doctrine:migrate --up'
alias d.gmd='s doctrine:generate-migrations-diff'
alias d.gm='s iGivings:generate-migration'
alias d.sm='s iGivings:migration-version-set'

alias d.bc='s doctrine:build --all-classes'
alias d.ba='s doctrine:build --all'
alias d.dl='s doctrine:data-load'

#terminal
alias tarf='tar -cvzf'
alias untarf='tar -zxvf'
alias untar='tar -zxvf'
alias la='ls -alh --color=auto'
alias ll='ls -lh --color=auto'
alias cdln='cd -P'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
function take {
  mkdir $1
  cd $1
}

#alias rmdir-empty='find /home/mymusic -type d -print0 | xargs -0 rmdir --ignore-fail-on-non-empty --parents'
function rmdir-empty {
  find $1 -type d -print0 | xargs -0 rmdir --ignore-fail-on-non-empty --parents
}
alias nn=nano
alias ea='nano ~/bin/dotfiles/bash/aliases && reload'
alias ee='nano ~/bin/dotfiles/bash/env'
alias ec='nano ~/bin/dotfiles/bash/config'

alias h='history'
alias reload='source ~/bin/dotfiles/bash/aliases'

#git
alias ga='git add -A .'
alias g='git status'
function gg {
  git commit -m "$*"
}
alias gga='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'

alias g.c='git checkout'
alias g.r='git reset'
alias g.f='git fetch'
alias g.p='git push'
alias g.a='git add'
alias g.cp='git cherry-pick'

function g.ff {
  command='git rebase origin/'
  command+=`g.br`
  $command
}
