#!/bin/bash


#lamp
alias a2='sudo service apache2'
alias vhosts='sudo mc /etc/apache2/'
alias debug="export XDEBUG_CONFIG='idekey=PHPSTORM remote_host=localhost';export SERVER_PORT=80;export SERVER_NAME=localhost;export REQUEST_URI=localhost"
alias undebug="unset XDEBUG_CONFIG;unset SERVER_PORT;unset SERVER_NAME;unset REQUEST_URI"

#symfony common (1, 2)
function sf-ver {
  if [ -f ./symfony ]
  then
      echo 1
  elif [ -f ./app/console ]
  then
      echo 2
  else
      echo 0
  fi
}

function s {
  if [ "$(sf-ver)" = '1' ]
  then
      ./symfony $*
  elif [ "$(sf-ver)" = '2' ]
  then
      ./app/console $*
  else
     echo "No symfony project found"
  fi
}

alias s.cc="s cache:clear"
alias s.gb='s generate:bundle'
alias s.ge='s doctrine:generate:entity'
alias s.gc='s doctrine:generate:crud'
alias s.su='s doctrine:schema:update --force'
alias s.fl='s doctrine:fixtures:load'

function d.da {
  s doctrine:query:dql "$*" --hydrate="array"
}

function d.d {
    if [ "$(sf-ver)" = '1' ]
    then
        ./symfony doctrine:dql "$*"
    elif [ "$(sf-ver)" = '2' ]
    then
        ./app/console doctrine:query:dql "$*"
    else
        echo "No symfony project found"
    fi
}

#symfony 1
alias d.m='s doctrine:migrate'
alias d.gmd='s doctrine:generate-migrations-diff'
alias d.gm='s iGivings:generate-migration'
alias d.smv='s iGivings:migration-version-set'
alias d.bc='s doctrine:build --all-classes'
alias d.dl='s doctrine:data-load'
function d.ba {
  s doctrine:build --all
  d.smv
}

#terminal
alias tarf='tar -cvzf'
alias untarf='tar -zxvf'
alias untar='tar -zxvf'
alias la='ls -alh --color=auto'
alias ll='ls -lh --color=auto'
alias cdln='cd -P'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
function take {
  mkdir $1
  cd $1
}

alias ea='nano ~/bin/dotfiles/bash/aliases && reload'
alias ee='nano ~/bin/dotfiles/bash/env'
alias ec='nano ~/bin/dotfiles/bash/config'

alias h='history'
alias reload='source ~/bin/dotfiles/bash/aliases'

#git
function g.br {
  br=`git branch | grep "*"`
  echo ${br/* /}
}

alias ga='git add -A .'
alias g='git status'
function gg {
  git commit -m "$*"
}
alias gga='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'

alias g.c='git checkout'
alias g.r='git reset'
alias g.rb='git rebase'
alias g.f='git fetch'
alias g.p='git push'
alias g.a='git add'
alias g.cp='git cherry-pick'
alias g.m='git merge'
alias g.s='git stash'
alias g.sp='git stash pop'
alias g.l='git log'
alias g.b='git branch'
function g.ff {
  c='git rebase origin/'
  b=`git branch | grep "*"`
  c+=${b/* /}
  $c
}
